### ISSUE TITLE
All proxies down (there was only one: zeronet.now.im)

### ISSUE THREAD

**Issue by tlaurion** [AceLewis/AceZeroProxy#16]
@AceLewis 
1- Is there some kind of keep alive on referred instances?
Edit: read the doc. 100% client side so I guess not. Is there any reference on open proxy lists that could be eaten and injected into AceZeroProxy referred proxies?
1- Is there a procedure for people to fire up new instances easily to permit people to participate in clearnet ZeroNet accessibility? Pointing to one that goes down doesn't resolve the accessibility issue not makes this resilient, nor pointing to https://zero.acelewis.com/ to have people redirected to a working proxy for a long while, the list having gone from 3 to 1 referred proxy.

**Comment by AceLewis** [comment]
I just found two proxies that are working and added them to the list. I have a list of dead proxies but don't have access to any public resources of ZeroNet proxies. As far as I am aware the list I maintain here is the only public one. I would love to add more proxies.

I made a (now dated) video showing how to set up a proxy, if people make public proxies they can be added to the list. The issue is not many people want to run the proxies. I have a Python script that can check the proxies to see if they are alive, I will add that to the project this weekend.

**Comment by tlaurion** [comment]
@AceLewis I would really love for you/others to drop some documentation guide.
My site: https://zero.acelewis.com/#1DMb3CV66qZPwJqkgm4z12nu8BrAwDoD4g/ is not cached by other members, probably because they are blocking off additional sites per configuration. This redirects to https://0net-preview.com/1DMb3CV66qZPwJqkgm4z12nu8BrAwDoD4g/ which doesntr cache website, as opposed to **zeronet.now.im** which did....

How do we organize around this?

**Comment by AceLewis** [comment]
Not much documantation is needed for this site, it just redirects you to a proxy in this list: https://github.com/AceLewis/AceZeroProxy/blob/gh-pages/_data/zeronet_proxies.csv

People need to run open zeronet proxies, I can't control if the person hosting the proxy allows random sites to be added. If there were more proxies running I would add an open one (one that allows random sites to be added) over a closed one. https://z.wwwww.wtf/ is open but not that stable and is slow, https://0net-preview.com/ is stable and fast but not open, it is not clear what is a better option and time will tell how long they run for.

The main problem of the project is there are not many/any public, open and stable proxies, if you find some you can commit them. This is a problem I can't control, I will not be running a public proxy.
